spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: my-market-app

  r2dbc:
    url: ${R2DBC_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    url: ${JDBC_DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
#      username: ${REDIS_USER:redis}
      password: ${REDIS_USER_PASSWORD:redispass}
  cache:
    redis:
      time-to-live: PT1M    # TTL по умолчанию для кеше

  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: ${ISSUER_URL:http://localhost:8081}
        registration:
          shop-client:
            provider: spring
            client-id: shop-client
            client-secret: ${SHOP_OAUTH_SECRET:shop-secret}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
            scope: payment
payment:
  service:
    url: ${PAYMENT_API_URL:http://localhost:8082}